server:
  port: 8830
spring:
  application:
    name: all-club-wx
  redis:
    # Redis数据库索引（默认为0）
    database: 4
    # Redis服务器地址
    host: 47.108.81.82
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: TXFtxf1121512752
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0