server:
  port: 8810
spring:
  application:
    name: all-club-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #数据库密码加密
    password: WqwtJTHxVprKmBkr7MLTtV7r9i9FcVUx7Hs4UhzhAdegjcUkDBN7mD8LXNmDGDXeUNqlVH6YS9eLgS7FUQ2vpQ==
    url: jdbc:mysql://47.108.81.82:3306/txf_club_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      max-active: 100
      max-wait: 60000
      min-idle: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
      # druid加密配置
      connection-properties: config.decrypt=true;config.decrypt.key=${publicKey}

logging:
  config: classpath:log4j2-spring.xml
#druid加密公钥
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL1elCJ5I0u1epkr7bkzUykLXuu5Tu9Nm2R9pdy7K1D+smYVo7rR1Ezu4b1osbriIr7xmUQepPc+a8JPnSVVMzMCAwEAAQ==

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-32
  # 是否输出操作日志
  is-log: true
  token-prefix: txf