server:
  port: 8800

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #数据库密码加密
    password: WqwtJTHxVprKmBkr7MLTtV7r9i9FcVUx7Hs4UhzhAdegjcUkDBN7mD8LXNmDGDXeUNqlVH6YS9eLgS7FUQ2vpQ==
    url: jdbc:mysql://127.0.0.1:3306/txf_club_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      max-active: 100
      max-wait: 60000
      min-idle: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
      # druid加密配置
      connection-properties: config.decrypt=true;config.decrypt.key=${publicKey}
#  elasticsearch:
#    rest:
#      uris: http://47.108.252.155:9200
#      username: elastic
#      password: TXFtxf1121512752
es:
  cluster:
    esConfigs[0]:
      name: dbcee53dd3da
      nodes: 127.0.0.1:9200 #一个集群可以有多个ip
      username: elastic
      password: 123456
rocketmq:
  name-server: 127.0.0.1:9876 #连接的我的虚拟机里面安装的mq
  producer:
    group: test-group

logging:
  config: classpath:log4j2-spring.xml
#druid加密公钥
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL1elCJ5I0u1epkr7bkzUykLXuu5Tu9Nm2R9pdy7K1D+smYVo7rR1Ezu4b1osbriIr7xmUQepPc+a8JPnSVVMzMCAwEAAQ==

# 这里注释掉了，因为自定义了更好看的，详情见infra层的config里面
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis-plus日志打印在控制台

# xxl-job
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:7900/xxl-job-admin
    accessToken: default_token
    # 执行器的基本属性
    executor:
      appname: txf-club-subjcet
      address:
      ip: 127.0.0.1
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30